### ISSUE TITLE
Example: irradiation_planar fails

### ISSUE THREAD

**Issue by SinuoZhang** [SiLab-Bonn/Scarce#3]
``` bash
Traceback (most recent call last):
  File "E:\intership\Scarce-master\scarce\examples\irradiation_planar.py", line 122, in <module>
    transient_irrad()
  File "E:\intership\Scarce-master\scarce\examples\irradiation_planar.py", line 75, in transient_irrad
    _, _, I_ind_e, I_ind_h, T, _ = dd.solve(p0, q0, dt, n_steps)
ValueError: too many values to unpack
```

**Comment by SinuoZhang** [comment]
this issue is currently solved by adding two more ",_" before the "=", since the "dd.solve()" returns 8 objects
