### ISSUE TITLE
cce_3D fails

### ISSUE THREAD

**Issue by SinuoZhang** [SiLab-Bonn/Scarce#4]
bash
'''
Traceback (most recent call last):
  File "E:\intership\Scarce-master\scarce\examples\cce_3D.py", line 126, in <module>
    cc_efficiency(biases, n_effs, t_e_trappings, t_h_trappings, t_e_1_trapping, t_h_1_trapping)
  File "E:\intership\Scarce-master\scarce\examples\cce_3D.py", line 46, in cc_efficiency
    edge_x, edge_y, charge = cc(bias=-20,
UnboundLocalError: local variable 'cc' referenced before assignment
'''

**Comment by SinuoZhang** [comment]
A new "simple" version has been written. The charge collection (efficiency) maps for one pixel has been plotted

**Comment by DavidLP** [comment]
If you think that you fixed a bug, I would reomment to create a `development` branch and push your changes to it.
