### ISSUE TITLE
Example: cce_planar fails

### ISSUE THREAD

**Issue by SinuoZhang** [SiLab-Bonn/Scarce#5]
```bash
Traceback (most recent call last):
  File "E:\intership\Scarce-master\scarce\examples\cce_planar.py", line 226, in <module>
    myfile.append('Fluence\tBias\tN_eff_0\tN_eff\tt_e\tt_h\n')
AttributeError: 'file' object has no attribute 'append'
```

**Comment by SinuoZhang** [comment]
'''
Traceback (most recent call last):
  File "E:\intership\Scarce\scarce\examples\cce_planar.py", line 242, in <module>
    t_h_trappings=t_h_trappings)
  File "E:\intership\Scarce\scarce\examples\cce_planar.py", line 102, in cc_efficiency
    pot_w_descr=pot_w_descr, mesh=mesh, smoothing=smoothing, pot_descr=pot_descr)
ValueError: need more than 2 values to unpack
'''
